Repository AY2122S2-CS2103T-T13-1/tp, pull requests merged in 2022-04, with the labels that each got.

#117 Fix JavaFX error
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PetListCard.fxml
  src/main/resources/view/PetListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: bug, severity.Low

#159 #155 - Restrict user input for owner name and name fields
  docs/UserGuide.md
  src/main/java/seedu/address/model/pet/Name.java
  src/main/java/seedu/address/model/pet/OwnerName.java
  src/main/java/seedu/address/model/pet/Phone.java
  src/test/data/JsonSerializableAddressBookTest/typicalPetsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/pet/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/pet/NameTest.java
  src/test/java/seedu/address/model/pet/OwnerNameTest.java
  src/test/java/seedu/address/model/pet/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPets.java
Labels: bug, enhancement

#163 Fix edit command duplicate pets issue
  src/main/java/seedu/address/model/pet/Pet.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/pet/PetTest.java
Labels: type.Bug

#164 Fix issues from PE
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DietCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/pet/Diet.java
  src/main/java/seedu/address/storage/JsonAdaptedPet.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/DietCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug

#170 Update Appointment error message
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug, enhancement

#165 Update soloplxya.md to reflect personal contributions to WoofAreYou (PPP update)
  docs/team/soloplxya.md
Labels: documentation

#166 Update PPP to reflect updated contributions
  docs/team/tobihy.md
Labels: documentation

#173 Fix text limit in GUI and overflow errors
  src/main/java/seedu/address/ui/AppointmentInfoLabel.java
  src/main/java/seedu/address/ui/AppointmentLabel.java
  src/main/java/seedu/address/ui/AppointmentTag.java
  src/main/java/seedu/address/ui/AttendanceTag.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/DietLabel.java
  src/main/java/seedu/address/ui/DietTag.java
  src/main/java/seedu/address/ui/PetCard.java
  src/main/java/seedu/address/ui/TextFieldLimited.java
  src/main/java/seedu/address/ui/TransportTag.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PetListCard.fxml
Labels: bug

#171 Update charge message to include year
  src/main/java/seedu/address/logic/commands/ChargeCommand.java
  src/test/java/seedu/address/logic/commands/ChargeCommandTest.java
Labels: bug

#167 Fix invalid `present` command causing exception
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AbsentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/PresentAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AbsentAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PresentAttendanceCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PresentAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AbsentAttendanceCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PresentAttendanceCommandParserTest.java
Labels: bug

#177 Restrict parse tags function
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/FilterUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ChargeCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DietCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/pet/Pet.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/commons/util/FilterUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPetDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/EditPetDescriptorBuilder.java
Labels: bug, documentation, enhancement

#176 Update invalid index messages
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ChargeCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DietCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/pet/Address.java
  src/main/java/seedu/address/model/pet/Diet.java
  src/test/java/seedu/address/logic/parser/AbsentAttendanceCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ChargeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DietCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/PresentAttendanceCommandParserTest.java
Labels: bug

#182 Edit default GUI settings and fix minor nit
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: bug, enhancement

#179 Update developmentGuide diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ChargeCommand.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ChargeSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/charge.png
  src/main/java/seedu/address/logic/commands/ChargeCommand.java
Labels: documentation

#180 Let's add testcases for invalid indexes and appointment parser class
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DietCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: enhancement

#185 Fix single-character not accepted bug for ownername and name.
  src/main/java/seedu/address/model/pet/Name.java
  src/main/java/seedu/address/model/pet/OwnerName.java
  src/test/java/seedu/address/model/pet/NameTest.java
  src/test/java/seedu/address/model/pet/OwnerNameTest.java
Labels: bug

#186 fixed UserGuide command summary
  docs/UserGuide.md
Labels: bug, documentation

#196 Branch fix ppp
  docs/team/tobihy.md
Labels: documentation

#194 Update DG for attendance feature
  docs/DeveloperGuide.md
  docs/diagrams/AttendanceHashMapClassDiagram.puml
  docs/images/AttendanceHashMapClassDiagram.png
  src/main/java/woofareyou/storage/JsonAdaptedAttendance.java
Labels: documentation

#198 Update index.md
  docs/index.md
Labels: documentation
