Repository AY2122S2-CS2103T-T13-1/tp, pull requests merged in 2022-03, with the labels that each got.

#35 Update AboutUs.md
  docs/AboutUs.md
  docs/images/tobihy.png
Labels: type.Task

#36 Add skeletal PPP
  docs/team/tobihy.md
Labels: type.Task

#37 Set up project website
  README.md
  docs/AboutUs.md
  docs/images/Ui.png
  docs/images/dineshraj555.png
  docs/team/dineshraj555.md
Labels: type.Task, priority.High

#40 Update UserGuide with introduction and Ui.png
  docs/UserGuide.md
Labels: type.Task, priority.High

#42 Update skeletal PPP
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/team/soloplxya.md
  docs/team/tiffanylin21.md
Labels: type.Task, priority.High

#55 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#56 Update site-wide settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task

#57 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#60 Update index.md
  docs/index.md
Labels: type.Task

#62 Update add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/pet/OwnerName.java
  src/main/java/seedu/address/model/pet/Pet.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPet.java
  src/main/java/seedu/address/ui/PetCard.java
  src/main/resources/view/PetListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPetDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/pet/PetTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPetTest.java
  src/test/java/seedu/address/testutil/PetBuilder.java
  src/test/java/seedu/address/testutil/PetUtil.java
  src/test/java/seedu/address/testutil/TypicalPets.java
Labels: type.Task, priority.High

#64 Add diet command to allow pet owners to put remarks for their pet's dietary concerns
  src/main/java/seedu/address/logic/commands/DietCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DietCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/pet/Diet.java
  src/main/java/seedu/address/model/pet/Pet.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPet.java
  src/main/java/seedu/address/ui/PetCard.java
  src/main/resources/view/PetListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPetAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPetsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePetsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPetsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPetsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DietCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPetTest.java
  src/test/java/seedu/address/testutil/EditPetDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PetBuilder.java
  src/test/java/seedu/address/testutil/PetUtil.java
  src/test/java/seedu/address/testutil/TypicalPets.java
Labels: priority.High

#65 Update delete and find commands, UserGuide and GUI
  copyright.txt
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/pet/Pet.java
  src/main/java/seedu/address/model/pet/UniquePetList.java
  src/main/java/seedu/address/model/pet/exceptions/DuplicatePetException.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/app_icon.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
Labels: type.Task, priority.High

#70 Update AddressBookStorage to create a file for each pet
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
Labels: priority.High

#72 Implement sort functionality for WoofAreYou
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/pet/Name.java
  src/main/java/seedu/address/model/pet/UniquePetList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: type.Story

#77 Bug fix petname
  src/main/java/seedu/address/model/pet/Address.java
  src/main/java/seedu/address/model/pet/Diet.java
  src/main/java/seedu/address/model/pet/Name.java
  src/main/java/seedu/address/model/pet/OwnerName.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/pet/PetTest.java
Labels: bug

#79 Update DeveloperGuide with sort feature implementation
  docs/DeveloperGuide.md
  docs/diagrams/Sort.puml
  docs/diagrams/SortActivityDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: documentation

#81 Branch update dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/FilterActivityDiagram.png
  docs/images/FilterSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
Labels: documentation

#80 Improve attendance command implementation
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AbsentAttendanceSequenceDiagram.puml
  docs/diagrams/AttendanceActivityDiagram.puml
  docs/images/AbsentAttendanceSequenceDiagram.png
  docs/images/AttendanceActivityDiagram.png
  src/main/java/seedu/address/commons/util/AttendanceUtil.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AbsentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/DietCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/PresentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AbsentAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DietCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PresentAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/attendance/AbsentAttendanceEntry.java
  src/main/java/seedu/address/model/attendance/AttendanceEntry.java
  src/main/java/seedu/address/model/attendance/MissingAttendanceEntry.java
  src/main/java/seedu/address/model/attendance/PresentAttendanceEntry.java
  src/main/java/seedu/address/model/pet/Appointment.java
  src/main/java/seedu/address/model/pet/AttendanceHashMap.java
  src/main/java/seedu/address/model/pet/Pet.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedPet.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/ui/AttendanceTag.java
  src/main/java/seedu/address/ui/PetCard.java
  src/main/resources/view/PetListCard.fxml
  src/test/java/seedu/address/commons/util/AttendanceUtilTest.java
  src/test/java/seedu/address/logic/commands/AbsentAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/PresentAttendanceCommandTest.java
  src/test/java/seedu/address/model/attendance/AbsentAttendanceEntryTest.java
  src/test/java/seedu/address/model/attendance/AttendanceEntryTest.java
  src/test/java/seedu/address/model/attendance/PresentAttendanceEntryTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPetTest.java
  src/test/java/seedu/address/testutil/PetBuilder.java
  src/test/java/seedu/address/testutil/PresentAttendanceDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPets.java
Labels: priority.High

#85 Fix time validity checks
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/AttendanceUtil.java
  src/main/java/seedu/address/logic/commands/PresentAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/PresentAttendanceCommandParser.java
  src/main/java/seedu/address/model/attendance/PresentAttendanceEntry.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
  src/test/java/seedu/address/model/attendance/PresentAttendanceEntryTest.java
Labels: bug

#86 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#87 Add undo functionality to WoofAreYou
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: priority.High

#89 Update sort command to sort by appointment
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/pet/UniquePetList.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: type.Enhancement, priority.Medium

#97 Update GUI to include transport arrangements
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/AttendanceUtil.java
  src/main/java/seedu/address/logic/commands/AbsentAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/PresentAttendanceCommand.java
  src/main/java/seedu/address/model/attendance/AbsentAttendanceEntry.java
  src/main/java/seedu/address/model/attendance/AttendanceEntry.java
  src/main/java/seedu/address/model/attendance/MissingAttendanceEntry.java
  src/main/java/seedu/address/model/attendance/PresentAttendanceEntry.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/AttendanceTag.java
  src/main/java/seedu/address/ui/PetCard.java
  src/main/java/seedu/address/ui/TransportTag.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PetListCard.fxml
  src/test/java/seedu/address/logic/commands/AbsentAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/PresentAttendanceCommandTest.java
  src/test/java/seedu/address/model/pet/AttendanceHashMapTest.java
  src/test/java/seedu/address/testutil/AbsentAttendanceDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PetBuilder.java
  src/test/java/seedu/address/testutil/PresentAttendanceDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPets.java
Labels: enhancement, type.Task

#102 Update GUI to wrap command result text
  src/main/resources/view/ResultDisplay.fxml
Labels: bug, severity.Medium

#99 Update sort command to sort by drop off time and pick up time
  docs/team/dineshraj555.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/SortUtil.java
  src/main/java/seedu/address/model/attendance/AttendanceEntry.java
  src/main/java/seedu/address/model/pet/Appointment.java
  src/main/java/seedu/address/model/pet/UniquePetList.java
  src/main/java/seedu/address/model/pet/comparator/PetDropOffTimeComparator.java
  src/main/java/seedu/address/model/pet/comparator/PetPickUpTimeComparator.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/model/pet/AppointmentTest.java
  src/test/java/seedu/address/model/pet/NameTest.java
  src/test/java/seedu/address/model/pet/OwnerNameTest.java
  src/test/java/seedu/address/model/pet/comparator/PetDropOffTimeComparatorTest.java
  src/test/java/seedu/address/model/pet/comparator/PetPickUpTimeComparatorTest.java
  src/test/java/seedu/address/testutil/ComparatorUtil.java
Labels: enhancement, priority.High

#109 Update GUI appointment info colour code
  src/main/java/seedu/address/logic/commands/AppointmentCommand.java
  src/main/java/seedu/address/ui/AppointmentInfoLabel.java
  src/main/java/seedu/address/ui/AppointmentLabel.java
  src/main/java/seedu/address/ui/PetCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PetListCard.fxml
Labels: enhancement

#108 Update UG
  docs/UserGuide.md
Labels: documentation, priority.High

#111 Fix GUI bug in fullscreen mode
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PetListCard.fxml
Labels: bug

#107 Set a character limit to user input in GUI
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/TextFieldLimited.java
  src/main/resources/view/CommandBox.fxml
Labels: bug
